---
# tasks file for storage

- name: Copy longhorn manifest to first master
  template:
    src: "longhorn.yaml.j2"
    dest: "/var/lib/rancher/k3s/server/manifests/longhorn.yaml"
    owner: root
    group: root
    mode: 0644
  when: ansible_host == hostvars[groups['master'][0]]['ansible_host'] | default(groups['master'][0])